#!/bin/bash -e

outputfile="ots-service/build/libs/$GO_PACKAGE_LOCAL_NEXUS_OTS_SERVICE_BINARY_ARTIFACT_ID-$GO_PACKAGE_LOCAL_NEXUS_OTS_SERVICE_BINARY_VERSION.$GO_PACKAGE_LOCAL_NEXUS_OTS_SERVICE_BINARY_PACKAGING"

echo $outputfile

curl -o  $outputfile $GO_PACKAGE_REPONAME_PKGNAME_LOCATION

