# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative '../../../ruby/lib/vagrant_helper'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos64"

  helper = VagrantHelper.new(__FILE__, "../../../environments")

  config.vm.network "private_network", ip: helper.ip

  config.vm.synced_folder "../../../", "/ots"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

end

