require 'rake'
require 'rspec/core/rake_task'
require 'rubygems'
require 'json'

env = ENV['env']

config = JSON.parse open('../environments/%s.json' %[env]).read

task :spec => 'spec:all'

namespace :spec do
  task :all => config.keys.map { |role_name| 'spec:' + role_name }

  config.keys.each do |group_name|
    config[group_name].keys.select { |key| key != 'vars' }.each do |host_name|

      role = group_name
      host = config[group_name][host_name]['host']
      user = config[group_name][host_name]['user']
      pass = config[group_name][host_name]['pass']


      desc "Run serverspec to #{host}"
      RSpec::Core::RakeTask.new(role) do |task|
        ENV['TARGET_HOST'] = host
        ENV['TARGET_SSH_USER'] = user
        ENV['TARGET_SSH_PASS'] = pass
        task.pattern = "spec/#{role}/*spec.rb"
      end
    end
  end
end