---

 - name: detect existing ots service container
   shell: >
     docker ps -f="name={{ ots_service_container_name }}" -aq
   register: existing_container_id

 - debug: msg="{{ existing_container_id }}"

 - name: stop existing ots service container
   shell: >
     docker stop {{ item }}
   with_items: existing_container_id.stdout_lines
   when: existing_container_id.stdout_lines != []

 - name: remove existing ots service container
   shell: >
     docker rm {{ item }}
   with_items: existing_container_id.stdout_lines
   when: existing_container_id.stdout_lines != []


 - name: start ots service container
   shell: >
     docker run --name="{{ ots_service_container_name }}" -d -p={{ ots_service_port }}:8080 hippoom/restfriedchicken-ots-service:{{ots_service_tag| default('latest')}}


